### ISSUE TITLE
contributing.md: requested date format incorrect

### ISSUE THREAD

**Issue by jethron** [Readify/DevEvents#69]
contributing.md:
> Ensure dates are in dd/mm/yyyy format (in case we want to parse this data later). Use TBC if the date is unconfirmed or unknown.

This seems to only be in-place for the pre-2018 data. Consensus in readme.md from 2018 onwards seems to have settled on `dd-mmm-yyy` (`%d-%b-%Y`) instead.

**Comment by luizbon** [comment]
Closing this issue as it was fixed on #77
