### ISSUE TITLE
Reorganize the content

### ISSUE THREAD

**Issue by rbanks54** [Readify/DevEvents#72]
Now that we have a lot of events in the list, we should improve how we manage the list.

I'm proposing we psuedo-archive older events to stop the listing page from growing too long and having a large signal-to-noise ratio.
I'm also proposing a reordering of information to make it easier to find things people are interested in.

I suggest we do the following:
- [x] Split out previous years (e.g. 2017) into their own year specific pages, with a link from the main listing page
- [ ] Re-organize the main page to show events in a year in reverse date order
- [x] Have separate tables for each upcoming year (2018, 2019, etc.)
- [ ] Add a table of contents to jump to specific years as well as the list of recurring and completed events
- [x] Split the table for the current year (currently 2018) into upcoming 2018 events and completed 2018 events. We can then remove the strikethrough formatting as it makes things harder to read.

**Comment by vatsalyagoel** [comment]
Slightly different proposal, What if we were to reorganize the structure into a JSON file and have a process to generate the MD file for us.

Pro: Structured and Easily Parse-able data
Con: A bit more work on the User's end to generate the content.

We could have a build process which does the .md generation for us and thus keeping the PR flow simple.

**Comment by swalladge** [comment]
Another idea:

- store events in separate yaml formatted files
- use jekyll with templates to generate a site containing a listing of these events

Pros:

- github pages == no manual processing to generate final product
- easy to include more data about events
- one event == one file == profit?
- result displayed on a neat website
- easy to split events into one year per page, auto hiding of past events with js, etc. etc.

Cons:

- more code just to display a list of events
- no longer a simple plain text list of events

Inspired by the [pycon au 2018](https://github.com/pyconau/2018.pycon-au.org) website which does this for the schedule pages.

**Comment by rbanks54** [comment]
When we set the event list up, we wanted to make sure that the markdown was the only thing we needed. This way it would be easy to contribute to and would be approachable by anyone.
Restructuring the markdown is a pretty simple step, and much less work and maintenance than needing to setup up a build server.

It's something we could look at again down the track, especially the GHPages approach, but for now I'd like us to keep things as simple as possible and avoid mixing a restructuring of data with a different way of representing that data. Does that make sense?

**Comment by rbanks54** [comment]
Closing this issue as the two incomplete list items aren't needed just now. We'll give it some time and revisit if needed.
